### ISSUE TITLE
[Request] [Report-Status] Huawei G7-L01 | ABout Version 

### ISSUE THREAD

**Issue by gigoplast** [werasik2aa/UnlockedHuaweiBootloader#1]
Please is there a Dump __ Under Android_6.0.1_**EMUI**_4.0___ .
Is Files "SBL1 ABOOT" Under Android_5.1.1_**EMUI**_3.1___ .

🥇 🥇  _Thank You  So Much_ For  Years Looking to **UNLOCK__IT**  without a CHANCE 🥇  🥇 

                                                                                💯  👍

**Comment by werasik2aa** [comment]
hm , should be

**Comment by werasik2aa** [comment]
https://addrom.com/collection-stock-rom-for-huawei-model/
here board firmwares

**Comment by werasik2aa** [comment]
the loaders g7-l01 only fro l01

**Comment by gigoplast** [comment]
I Have Try it Both
First  "G7-L01.zip" under__commit [4afb12f] 'https://github.com/werasik2aa/UnlockedHuaweiBootloader/commit/4afb12f158ed8ab45614564b9d0778ba390b780d'
Second "G760-LXX.zip" under__commit [2aeef3b] 'https://github.com/werasik2aa/UnlockedHuaweiBootloader/blob/2aeef3bc4b30477e8e4c4e827fa7ae62771308f1/G760-LXX.zip'
 I Have Huawie Ascend G7-L01 under C185B320 EMU-3.1 "5.1.1"(android)  & C185B510 EMUI-4.0 "6.0.1"(android) Flash Rom Archived and work 100% with Bootloader looked . Under knowledge of QFIL Operation i Dumped The 2 ROM "C185B320&C185B510"  5.1.1/6.0.1(android) Lolipop/marshmallow .


**0 chance**  "G7-L01.zip" under__commit [4afb12f] " With 2 Roms after upgrade sbl1&aboot. reboot at **fastboot** [mode locked] 
**50% chance**  "G760-LXX.zip" under__commit [2aeef3b]"  With Rom "C185B320" 5.1.1(android) .
STACK AT POWER'ON Huawie bootScreen Notice  .
![IMG_20240107_234239](https://github.com/werasik2aa/UnlockedHuaweiBootloader/assets/11947255/0e0fd563-7697-448b-a6d4-f4d53046f603)
![IMG_20240107_234244](https://github.com/werasik2aa/UnlockedHuaweiBootloader/assets/11947255/bf872fca-038d-4298-87f5-d3457e373b64). Fastboot (-Volum  power) Not-work reboot [![IMG_20240107_234244](https://github.com/werasik2aa/UnlockedHuaweiBootloader/assets/11947255/bf872fca-038d-4298-87f5-d3457e373b64)](url) 


Is There ACHANCE !

- [ ] G7-L01C185B320 5.1.1
- [ ] G7-L01C185B510 6.0.1

**Comment by werasik2aa** [comment]
Looks your device unlocked.

**Comment by werasik2aa** [comment]
https://4pda.to/forum/index.php?showtopic=753902&st=1420#entry127020635
Here same output

**Comment by werasik2aa** [comment]
But for working bootloader unlock needs to wipe data

**Comment by werasik2aa** [comment]
Extract this package .img (it's contains part of emmc dump)
https://github.com/werasik2aa/UnlockedHuaweiBootloader/blob/7cdbcef6033567eaf240763b2f50e90993502943/UnsortedBootloaders/G760-L03

**Comment by werasik2aa** [comment]
I added fixed G7-L03

**Comment by gigoplast** [comment]
Is There a Hack to Gain The Bootloader key with Fastboot ?

**Comment by gigoplast** [comment]
🥇 🥇 Thank You So Much For Years Looking to UNLOCK__IT without a CHANCE 🥇 🥇

**Comment by werasik2aa** [comment]
hm is my fixed package working?

**Comment by gigoplast** [comment]
ANY HELP WHOULD-BE APPRECIATED 
https://github.com/bkerler/edl/issues/490#issue-2079409433

**Comment by werasik2aa** [comment]
And you test my new updated unlock package about 5 days ago

**Comment by gigoplast** [comment]
I have a backup of userdata most importing data "2fa,crypto-account,..some application-config,.." uder EMUI 4.0.
i try it  G7-LXX Work  **_Perfectly_**  & i try som custom rom Lineageos Pac-rom every rom work Nice and i **Rooted** Both 
but when apply my userbackup everything Mess-UP . Last Think I wish To gain Root with an official ROM.
I Do that For HOBBIE

**Comment by werasik2aa** [comment]
It's not mine problem. It's huawei's side problem. On unlocked device userdata can not be restored by backup.
I'm closing this issue due unlock working.
