### ISSUE TITLE
[SOLVED] [NOT_NEED] [TESTING] I can help with a 710!

### ISSUE THREAD

**Issue by MeblIkea** [werasik2aa/UnlockedHuaweiBootloader#3]
Hello!
I have a Huawei P Smart 2020 in my drawer. It's using a Kirin 710, so it's FBLock, so it's basically a nice looking brick. At the footer of the page, you said "But i need a tester", I can help with giving you access to the phone via a dedicated computer (or just with doing it by myself).
Cheers!

**Comment by werasik2aa** [comment]
https://4pda.to/forum/index.php?showtopic=935415&st=4040#entry129709284

**Comment by MeblIkea** [comment]
@werasik2aa going to try that this week-end.
If it works, I will be super grateful! :D
